name: Build static book contents

on:
  workflow_call:

jobs:
  build:
    env:
      book_folder: ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
        with:
          path: ${{ env.book_folder }}
      - name: Checkout Converter
        uses: actions/checkout@v6
        with:
          repository: originlab/DocGHPagesConverter
          path: converter
      - name: Checkout Index
        uses: actions/checkout@v6
        with:
          repository: originlab/originlab.github.io
          path: converter/templates/wwwroot
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
      #- run: ls -l -R
      - name: Run Converter
        run: dotnet run --project converter/generator/generator.csproj -- ${{ env.book_folder }}
      - name: Upload book artifact
        uses: actions/upload-artifact@v7
        with:
          name: book
          path: ${{ env.book_folder }}/out

