name: Build static book contents

on:
  workflow_call:

jobs:
  build:
    env:
      is_index: ${{ github.event.repository.name == 'originlab.github.io' }}
      book_folder: ${{ case(github.event.repository.name == 'originlab.github.io', 'converter/templates/wwwroot/index', github.event.repository.name) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        if: ${{ !env.is_index }}
        uses: actions/checkout@v6
        with:
          path: ${{ env.book_folder }}
      - name: Checkout Converter
        uses: actions/checkout@v6
        with:
          repository: originlab/DocGHPagesConverter
          path: converter
      - name: Checkout Index
        uses: actions/checkout@v6
        with:
          repository: originlab/originlab.github.io
          path: converter/templates/wwwroot
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
      #- run: ls -l -R
      - name: Run Converter
        run: dotnet run --project converter/generator/generator.csproj -- ${{ env.book_folder }}
      - name: Upload book artifact
        uses: actions/upload-artifact@v7
        with:
          name: book
          path: ${{ case(env.is_index, 'converter/templates/wwwroot', env.book_folder) }}/out

