name: Publish all books to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  publish_index:
    uses: ./.github/workflows/publish_book.yml
    with:
      is_index: true

  setup_array:
    runs-on: ubuntu-slim
    outputs:
      sites: ${{ steps.set_sites.outputs.sites }}
    steps:
      - name: Writing the book url names into a sharable matrix input
        id: set_sites
        run: |
          {
            echo 'sites<<EOF'
            cat << 'JSON'
            [
              "user-guide",
              "tutorials",
              "quick-help",
              "origin-help",
              "x-function",
              "originc",
              "labtalk",
              "python",
              "externalpython",
              "com",
              "labview",
              "app",
              "appdev",
              "codebuild",
              "orglab",
              "license"
            ]
          JSON
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

  start_array:
    needs: [setup_array, publish_index]
    runs-on: ubuntu-slim
    environment: deploy
    env:
      GH_TOKEN: ${{ secrets.PAT_DOC_WORKFLOW }}
    strategy:
      matrix:
        site: ${{ fromJson(needs.setup_array.outputs.sites) }}
    steps:
      - name: Dispatch deploy.yml and capture the run url
        id: dispatch
        run: echo "deploy_run_url=$(gh workflow run deploy.yml --repo originlab/${{ matrix.site }})" >> "$GITHUB_ENV"
      - name: Save the run id
        run: echo "$deploy_run_url" | grep -oE "[0-9]+$" >> run_id.txt
      - uses: actions/upload-artifact@v7
        with:
          name: run_id-${{ matrix.site }}
          path: run_id.txt
          retention-days: 1

  get_result:
    needs: [setup_array, start_array]
    runs-on: ubuntu-slim
    environment: deploy_watch
    env:
      GH_TOKEN: ${{ secrets.PAT_DOC_WORKFLOW }}
    strategy:
      matrix:
        site: ${{ fromJson(needs.setup_array.outputs.sites) }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: run_id-${{ matrix.site }}
      - name: Set $deploy_run_id
        run: echo "deploy_run_id=$(cat run_id.txt)" >> "$GITHUB_ENV"
      - name: Watch the deployment
        run: gh run watch $deploy_run_id -R originlab/${{ matrix.site }} -i 10 --exit-status
      - name: Set $build_job_id
        run: echo "build_job_id=$(gh run view $deploy_run_id -R originlab/${{ matrix.site }} | grep 'publish_book / convert' | grep -oP '\(ID \K\d+')" >> "$GITHUB_ENV"
      - name: Print converter output
        run: >
          gh run view $deploy_run_id -j $build_job_id -R originlab/${{ matrix.site }} --log
          | awk '/generator\.dll"/ {f=1} /upload-pages-artifact/ {f=0} f'
          | cut -f3- | cut -d' ' -f2-
      - name: Print the book artifact summary
        run: >
          gh run view $deploy_run_id -j $build_job_id -R originlab/${{ matrix.site }} --log
          | awk '/Run actions\/upload-artifact|Finished uploading/{f=1} /Beginning upload|Artifact download/{f=0} f'
          | cut -f3- | cut -d' ' -f2-
      

        
