name: Build a book and deploy it to Pages

on:
  workflow_call:
    inputs:
      is_index:
        type: boolean

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  
  build:
    env:
      book_folder: ${{ github.event.repository.name }}${{ case(inputs.is_index, '/index', '') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Book
        if: ${{ !inputs.is_index }}
        uses: actions/checkout@v6
        with:
          path: ${{ env.book_folder }}
      - name: Checkout Index with Converter
        uses: actions/checkout@v6
        with:
          repository: originlab/originlab.github.io
          path: originlab.github.io
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
      #- run: ls -l -R
      - name: Run Converter
        run: dotnet run --project originlab.github.io/converter/generator/generator.csproj -- ${{ env.book_folder }} ${{ case(inputs.is_index, 'merge', '') }}
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: public_html

  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-slim
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

