name: Optimize the converter output

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Download converted artifact
        uses: actions/download-artifact@v8
        with:
          name: converted
          path: pages

      - name: Install tools
        run: |
          sudo apt-get install -y webp imagemagick minify parallel

      - name: Optimize still images
        run: >
          find pages/ \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \) -print0
          | parallel -0 'cwebp -q 80 {} -o {.}.webp && rm {}'

      - name: Optimize gif images
        run: >
          find pages/ -iname "*.gif" -print0
          | parallel -0 'mogrify -format webp {} && rm {}'

      - name: Optimize text
        run: |
          find pages/ -name "*.html" | parallel minify --html-keep-document-tags --html-keep-end-tags --html-keep-whitespace -o {} {}
          find pages/ -name "*.css"  | parallel minify -o {} {}
          find pages/ -name "*.js"   | parallel minify -o {} {}

      - name: Upload optimized artifact
        uses: actions/upload-artifact@v7
        with:
          name: optimized
          path: pages
          retention-days: 1
