name: Publish a book to Pages

on:
  workflow_call:
    inputs:
      is_index:
        type: boolean

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  
  convert:
    uses: ./.github/workflows/converter.yml
    with:
      run_tests: ${{ inputs.is_index }}
      is_index: ${{ inputs.is_index }}
      is_optimizing: true
      upload_converted: true

  optimize:
    needs: convert
    uses: ./.github/workflows/optimize.yml

  deploy:
    needs: optimize
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download optimized artifact
        uses: actions/download-artifact@v8
        with:
          name: optimized
          path: pages

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

