name: Publish a book to Pages

on:
  workflow_call:
    inputs:
      is_index:
        type: boolean

jobs:
  
  convert:
    uses: ./.github/workflows/converter.yml
    concurrency:
      group: "prepare_pages"
      cancel-in-progress: true
    with:
      run_tests: ${{ inputs.is_index }}
      is_index: ${{ inputs.is_index }}
      is_optimizing: true
      upload_converted: true

  optimize:
    needs: convert
    concurrency:
      group: "prepare_pages"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Download converted artifact
        uses: actions/download-artifact@v8
        with:
          name: converted
          path: pages

      - name: Checkout book.xml
        if: ${{ !inputs.is_index }}
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            en/${{ needs.convert.outputs.chm_name }}/book.xml
          sparse-checkout-cone-mode: false
          path: book

      - name: Install tools
        run: |
          sudo apt-get install -y webp minify parallel

      - name: Setup Optimization Helpers
        run: |
          cat << 'EOF' > helpers.sh
          get_source_path() {
            local file=$1
            
            if [ "${{ inputs.is_index }}" = "true" ]; then
              if [[ "$file" =~ ^[a-z]{2}/ ]] || [[ "$file" =~ ^programming/ ]]; then
                echo "index/${file}"
              else
                echo "converter/templates/wwwroot/${file}"
              fi
            else
              if [[ "$file" =~ ^[a-z]{2}/ ]]; then
                local lang="${file%%/*}"
                echo "${lang}/${{ needs.convert.outputs.chm_name }}/${file#*/}"
              else
                if [[ "$file" != */index.html ]]; then
                  echo "$file"
                  return
                fi

                # Find the url needed in the book.xml
                local dir_path="${file%/index.html}"
                local last_folder="${dir_path##*/}"
                local lang="en"
                local url=""

                if [[ "$last_folder" =~ ^[a-z]{2}$ ]]; then
                  lang="$last_folder"
                  url="${dir_path%/$lang}"
                else
                  url="$dir_path"
                fi
                
                local source_page_path

                local xml_path="book/en/${{ needs.convert.outputs.chm_name }}/book.xml"
                local u="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                local l="abcdefghijklmnopqrstuvwxyz"

                source_page_path=$(xmllint --xpath "string(//page[translate(@url, '$u', '$l')='$url']/@file)" "$xml_path" 2>/dev/null)
                
                echo "${lang}/${source_page_path}"
              fi
            fi
          }

          log_msg() {
            local status=$1; local file=$2; local msg=$3

            file="${file#pages/}"
            local source_file=$(get_source_path "$file")

            if [ $status -eq 0 ]; then
              if [ -n "$msg" ]; then
                echo "::notice file=$source_file::Optimized \`$file\` despite \`$msg\`"
              fi
            else
              echo "::warning file=$source_file::Skipped \`$file\` because \`$msg\`"
            fi
          }
          export -f get_source_path
          export -f log_msg
          EOF
          chmod +x helpers.sh

      - name: Optimize still images
        run: |
          source ./helpers.sh

          find pages/ \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \) -print0 | \
          parallel -0 -q bash -c '
            file="{}"
            output="{.}.webp"

            msg=$(cwebp -quiet -mt -lossless -q 100 "$file" -o "$output" 2>&1 >/dev/null)
            status=$?

            if [ $status -eq 0 ]; then rm "$file"; fi
            log_msg $status "$file" "$msg"
          '

          # Need some single quote to workaround a VS colorizer bug
          echo 'Done.'

      - name: Optimize gif images
        run: |
          source ./helpers.sh

          find pages/ -iname "*.gif" -print0 | \
          parallel -0 -q bash -c '
            file="{}"
            output="{.}.webp"

            msg=$(gif2webp -quiet -mt -min_size -q 100 "$file" -o "$output" 2>&1 >/dev/null)
            status=$?

            if [ $status -eq 0 ]; then rm "$file"; fi
            log_msg $status "$file" "$msg"
          '

          # Need some single quote to workaround a VS colorizer bug
          echo 'Done.'

      - name: Optimize text
        run: |
          source ./helpers.sh

          find pages/ \( -iname "*.html" -o -iname "*.css" -o -iname "*.js" \) -print0 | \
          parallel -0 -q bash -c '
            file="{}"
            if [[ "$file" == *.html ]]; then
              msg=$(minify --quiet --html-keep-document-tags --html-keep-end-tags --html-keep-whitespace -o "$file" "$file" 2>&1)
            else
              msg=$(minify --quiet -o "$file" "$file" 2>&1)
            fi
            log_msg $? "$file" "$msg"
          '

          # Need some single quote to workaround a VS colorizer bug
          echo 'Done.'

      - name: Upload optimized artifact
        uses: actions/upload-artifact@v7
        with:
          name: optimized
          path: pages
          retention-days: 1

  deploy:
    needs: optimize
    concurrency:
      group: "deploy_pages"
      cancel-in-progress: false
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download optimized artifact
        uses: actions/download-artifact@v8
        with:
          name: optimized
          path: pages

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

