name: Publish a book to Pages

on:
  workflow_call:
    inputs:
      is_index:
        type: boolean

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  
  convert:
    uses: ./.github/workflows/converter.yml
    with:
      run_tests: ${{ inputs.is_index }}
      is_index: ${{ inputs.is_index }}
      upload_pages: true

  optimize:
    needs: convert
    runs-on: ubuntu-latest
    steps:
      - name: Download Pages artifact
        uses: actions/download-artifact@v8
        with:
          name: github-pages
          path: pages

      - name: Install oxipng
        run: |
          oxipng_download_url=$(curl -s https://api.github.com/repos/oxipng/oxipng/releases/latest | rg -o -r '$1' '"browser_download_url": "(.+_amd64\.deb)"')"
          wget $oxipng_download_url
          sudo apt-get install ./*.deb

      - name: Optimize files
        run: |
          sudo apt-get install -y gifsicle minify parallel
          find pages/ -name "*.png" | parallel oxipng --strip safe {}
          find pages/ -name "*.gif" | parallel gifsicle --batch -O3 {}
          find pages/ -name "*.html" | parallel minify --mime=text/html -o {} {}
          find pages/ -name "*.css"  | parallel minify --mime=text/css -o {} {}
          find pages/ -name "*.js"   | parallel minify --mime=text/javascript -o {} {}

      - name: Upload optimized Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: pages

  deploy:
    needs: optimize
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

